---
# tasks file for devopsrob.kickstart
- tasks:
  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: present

  - name: Configure xinetd
    lineinfile:
      path="/etc/xinetd.d/tftp"
      regexp="disabled"
      line="disabled          = no"
      state=present
    notify: restart_xinetd

  - name: configure dnsmasq interface
    lineinfile:
      path="/etc/dnsmasq.conf"
      line="interface={{ interface }}"
      state="present"

  - name: configure dnsmasq domain
    lineinfile:
      path="/etc/dnsmasq.conf"
      line="domain={{ domain }}"
      state="present"
  
  - name: configure dnsmasq dhcp range
    lineinfile:
      path="/etc/dnsmasq.conf"
      line="dhcp-range={{ interface }},{{ dhcp_start }},{{ dhcp_end }},{{ dhcp_netmask }},{{dhcp_lease_time }}"
      state="present"

  - name: configure dnsmasq dhcp-boot
    lineinfile:
      path="/etc/dnsmasq.conf"
      line="dhcp-boot=pxelinux.0,pxeserver,{{ pxe_ip }}"
      state="present"

  - name: configure dnsmasq pxe gateway address
    lineinfile:
      path="/etc/dnsmasq.conf"
      line="dhcp-option=3,{{ pxe_gateway }}"
      state="present"

  - name: configure dnsmasq dns servers
    lineinfile:
      path="/etc/dnsmasq.conf"
      line="dhcp-option=6,{{ dns_1 }},{{ dns_2 }}"
      state="present"

  - name: configure dnsmasq pxe prompt
    lineinfile:
      path="/etc/dnsmasq.conf"
      line="pxe-prompt='{{ pxe_prompt }}',{{ pxe_prompt_timeout }}"
      state="present"

  - name: configure dnsmasq pxe service
    lineinfile:
      path="/etc/dnsmasq.conf"
      line="x86pc,{{ pxe_service_message }}"
      state="present"

  - name: Enable tftp boot in dnsmasq
    lineinfile:
      path="/etc/dnsmasq.conf"
      line="enable-tftp"
      state="present"

  - name: Set tftp root location in dnsmasq
    lineinfile:
      path="/etc/dnsmasq.conf"
      line="tftp-root=/var/lib/tftpboot"
      state="present"
