---
# tasks file for robraybarnes.apache
tasks:
   - name: Install packages for web server
     yum: 
     name: {{ item }} 
     state: present 
     update_cache: yes
     with_items:
       "httpd"
       "php"
       "python-certbot-apache"

  systemd:
    name: "{{ item }}"
    enabled: yes
    state: restarted
    daemon_reload: yes
    with_items:
    - "httpd"
    - "networkd"
    - "sshd"

  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "#Listen 12.34.56.78:80"
    line: "Listen 127.0.0.0:443"
    state: present
    notify:
      - restart apache
